# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoolBlue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoolBlue
  # Core
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'CoolBlueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoolBlueUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
